name: Build and Push to ECR, Update IaC Repo for Argo CD

on:
  push:
    branches:
      - main  # 본인의 Private Repository에서 main 브랜치에 푸시가 발생하면 트리거

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 클론
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. SSH 설정 (다른 사람의 Private Repo 접근용)
      - name: Setup SSH key for accessing IaC repo
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. AWS 로그인
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # 4. 도커 이미지 빌드
      - name: Build Docker image
        run: |
          TAG=${{ github.sha }}  # 현재 커밋의 SHA를 도커 이미지 태그로 사용
          DOCKER_BUILDKIT=1 docker build --no-cache --platform linux/amd64 \
            --build-arg SPRING_APPLICATION_NAME=oliveyoung \
            --build-arg SPRING_DATASOURCE_WRITER_URL=${{ secrets.SPRING_DATASOURCE_WRITER_URL }} \
            --build-arg SPRING_DATASOURCE_READER_URL=${{ secrets.SPRING_DATASOURCE_READER_URL }} \
            --build-arg SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
            --build-arg SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
            --build-arg SPRING_DATASOURCE_DRIVER_CLASS_NAME=${{ secrets.SPRING_DATASOURCE_DRIVER_CLASS_NAME }} \
            --build-arg SPRING_JPA_HIBERNATE_DDL_AUTO=${{ secrets.SPRING_JPA_HIBERNATE_DDL_AUTO }} \
            --build-arg SPRING_JPA_SHOW_SQL=${{ secrets.SPRING_JPA_SHOW_SQL }} \
            --build-arg SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=${{ secrets.SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT }} \
            --build-arg SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=${{ secrets.SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE }} \
            --build-arg SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=${{ secrets.SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE }} \
            --build-arg SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT=${{ secrets.SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT }} \
            --build-arg SPRING_DATASOURCE_HIKARI_MAX_LIFETIME=${{ secrets.SPRING_DATASOURCE_HIKARI_MAX_LIFETIME }} \
            --build-arg SPRING_DATA_REDIS_HOST=${{ secrets.SPRING_DATA_REDIS_HOST }} \
            --build-arg SPRING_DATA_REDIS_PORT=${{ secrets.SPRING_DATA_REDIS_PORT }} \
            -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/hachwimu-user:$TAG .

      # 5. ECR에 도커 이미지 푸시
      - name: Push to Amazon ECR
        run: |
          TAG=${{ github.sha }}
          REGION=ap-northeast-2
          REPOSITORY_NAME=hachwimu-user
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY_NAME:$TAG

      # 6. IaC Private Repo에 이미지 태그 업데이트 (Argo CD 자동 배포)
      - name: Update IaC Private Repo with new ECR tag
        env:
          TAG: ${{ github.sha }}
        run: |
          git clone https://github.com/JinsuYeo/hachwimu-iac.git  # 다른 사람의 Private IaC Repo URL 사용
          cd hachwimu-iac
          # user 이미지 태그 업데이트
          sed -i 's|image: .*hachwimu-user:.*$|image: '"${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/hachwimu-user:${TAG}"'|g' deployment.yaml
          # product 이미지 태그 업데이트
          sed -i 's|image: .*hachwimu-product:.*$|image: '"${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/hachwimu-product:${TAG}"'|g' deployment.yaml
          git add deployment.yaml
          git commit -m "Update image to $TAG"
          git push
