name: Build and Push to ECR, Update IaC Repo for Argo CD

on:
  push:
    branches:
      - main  # 본인의 Private Repository에서 main 브랜치에 푸시가 발생하면 트리거

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 클론
      - name: Checkout code
        uses: actions/checkout@v4  # 최신 버전으로 업데이트

      # 2. AWS 환경 변수 설정
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2  # AWS 자격증명 구성 액션 최신 버전 사용
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2  # AWS 리전 설정

      # 3. AWS ECR 로그인
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2  # 최신 버전
        with:
          registry-type: private  # ECR 리포지토리 타입

      # 4. 도커 이미지 빌드
      - name: Build Docker image
        run: |
          TAG=${{ github.sha }}  # 현재 커밋의 SHA를 도커 이미지 태그로 사용
          DOCKER_BUILDKIT=1 docker build --no-cache --platform linux/amd64 \
            --build-arg SSH_PRIVATE_KEY_BUILD="${{ secrets.SSH_PRIVATE_KEY_BUILD }}" \
            --build-arg SPRING_APPLICATION_NAME=oliveyoung \
            --build-arg SPRING_DATASOURCE_WRITER_URL=${{ secrets.SPRING_DATASOURCE_WRITER_URL }} \
            --build-arg SPRING_DATASOURCE_READER_URL=${{ secrets.SPRING_DATASOURCE_READER_URL }} \
            --build-arg SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
            --build-arg SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
            --build-arg SPRING_DATASOURCE_DRIVER_CLASS_NAME=${{ secrets.SPRING_DATASOURCE_DRIVER_CLASS_NAME }} \
            --build-arg SPRING_JPA_HIBERNATE_DDL_AUTO=${{ secrets.SPRING_JPA_HIBERNATE_DDL_AUTO }} \
            --build-arg SPRING_JPA_SHOW_SQL=${{ secrets.SPRING_JPA_SHOW_SQL }} \
            --build-arg SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=${{ secrets.SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT }} \
            --build-arg SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=${{ secrets.SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE }} \
            --build-arg SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=${{ secrets.SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE }} \
            --build-arg SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT=${{ secrets.SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT }} \
            --build-arg SPRING_DATASOURCE_HIKARI_MAX_LIFETIME=${{ secrets.SPRING_DATASOURCE_HIKARI_MAX_LIFETIME }} \
            --build-arg SPRING_DATA_REDIS_HOST=${{ secrets.SPRING_DATA_REDIS_HOST }} \
            --build-arg SPRING_DATA_REDIS_PORT=${{ secrets.SPRING_DATA_REDIS_PORT }} \
            -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/hachwimu-user:$TAG .

      # 5. ECR에 도커 이미지 푸시
      - name: Push to Amazon ECR
        run: |
          TAG=${{ github.sha }}
          REGION=ap-northeast-2
          REPOSITORY_NAME=hachwimu-user
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY_NAME:$TAG

      # 6. SSH 설정 (다른 사람의 Private Repo 접근용)
      - name: Setup SSH key for accessing IaC repo
        uses: webfactory/ssh-agent@v0.9.0  # 최신 버전
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_IAC }}  # IaC repo에 접근하는 SSH 키

      # 7. GitHub 사용자 설정
      - name: Set Git config
        run: |
          git config --global user.name "jaebinGit"
          git config --global user.email "tnwoql327@gmail.com"

      # 8. IaC Private Repo에 이미지 태그 업데이트 (Argo CD 자동 배포)
      - name: Clone IaC Repo and Update Tag
        run: |
          TAG=${{ github.sha }}
          
          # SSH 방식으로 리포지토리 클론
          git clone git@github.com:JinsuYeo/hachwimu-iac.git
          cd hachwimu-iac
          
          # 디버깅용 TAG와 패턴 확인
          echo "TAG is ${TAG}"
          
          # user 이미지 태그 업데이트
          echo "Updating image tag in deployment.yaml"
          sed -i "s|image: .*hachwimu-user:.*$|image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/hachwimu-user:${TAG}|g" deployment.yaml
          
          # 변경 내용 확인
          echo "Updated deployment.yaml:"
          cat deployment.yaml
          
          # Git에 변경 사항 추가 및 커밋
          git add deployment.yaml
          git status
          git diff
          git commit -m "Update image to ${TAG}" || echo "Nothing to commit"
          git push origin main || echo "Push failed"